const legal=[
['WIPO《伯尔尼公约》概要','说明国民待遇、自动保护与保护独立性等国际版权基本原则。','https://www.wipo.int/en/web/treaties/ip/berne/summary_berne'],
['WIPO 国际版权常见问题','版权具有地域性；不同使用地区仍应核对当地法律。','https://www.wipo.int/en/web/copyright/faq-copyright'],
['Creative Commons BY 4.0','允许分享与改编，但须适当署名、链接许可并说明是否修改。','https://creativecommons.org/licenses/by/4.0/deed.zh-hans'],
['Creative Commons BY-SA 4.0','除署名要求外，改编作品还需采用相同或兼容许可。','https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans'],
['Wikimedia Commons 外部复用指南','每张图片可能适用不同许可；应逐张核对署名、许可链接和改编要求。','https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/zh'],
['USAGov 政府资料版权说明','美国联邦网站中的内容并非全部属于公共领域，且境外使用可能适用不同规则。','https://www.usa.gov/government-copyright']
];
export default function Copyright(){return <><div className="page-head"><p className="eyebrow">COPYRIGHT · ATTRIBUTION · DISCLAIMER</p><h1>版权与免责声明</h1><p className="lead">本页说明本站如何聚合、整理和展示第三方图片与参考资料。它是透明度说明，不是法律意见。</p></div><article className="content"><h2>1. 权利归属</h2><p>站内第三方照片、图像、机构报告、论文和外部资料的版权及其他相关权利，归各自原作者、摄影者、机构或其他权利人所有；已明确属于公共领域或以 CC0 发布的材料不主张作者专有版权，但本站仍尽量保留出处与创作者信息。</p><p>本站对第三方内容不主张所有权，也不暗示原作者、Wikimedia Commons、USGS、BLM、Geoscience Australia 或其他机构认可、赞助本项目。</p><h2>2. 本站如何使用</h2><p>本站对可合法复用的资料进行中文整理、压缩、版面优化、教育性说明与主题聚合。每张第三方图片均在图鉴或知识页面附近标明作者/机构、许可名称以及原始文件页。除响应式缩放、压缩、裁切和色彩显示适配外，不改变照片所表达的地质对象；如以后进行实质改编，将在相应条目明确说明。</p><h2>3. 开放许可与公共领域</h2><ul><li><strong>CC BY：</strong>保留适当署名、原始链接、许可链接，并说明是否修改。</li><li><strong>CC BY-SA：</strong>除上述要求外，受许可约束的改编材料按相同或兼容许可发布。</li><li><strong>CC0 / Public Domain：</strong>通常无需版权许可，但公共领域判断可能因司法辖区而异，本站仍提供来源。</li><li><strong>美国政府资料：</strong>只有美国政府人员在公务范围内创作的特定作品通常属于美国法下的政府作品；政府网站上的第三方内容、徽标及境外使用不当然免责。</li></ul><h2>4. 国际版权原则</h2><p>WIPO 对《伯尔尼公约》的概要说明了国民待遇、自动保护和保护独立性原则。版权法具有地域性，合理使用、合理处理、数据库权、人格权、肖像权、隐私、商标及传统知识保护会因国家或地区不同而变化。因此本站的来源标注不能替代使用者在其所在地的法律核查。</p><h2>5. 本站原创部分</h2><p>除另有标注外，本站原创的中文概述、信息架构、字段设计、界面设计和程序代码按照仓库所载许可处理。第三方媒体不会因与本站原创文字共同出现而改变其原有许可。</p><h2>6. 更正与下架</h2><p>若你是权利人，认为署名、许可、来源、裁切方式或使用范围存在错误，请通过项目 GitHub 仓库提交问题，并提供作品链接、权利依据和期望处理方式。核实后将更正署名、替换内容或下架。</p><h2>7. 内容与专业免责声明</h2><p>图片不能完成矿物鉴定，教育内容也不能证明存在矿体、资源量、储量或经济价值。本站不提供法律、地质工程、采矿、安全或投资意见。用户须取得所在地土地与矿业许可，并由合资格专业人员及实验室复核重要结论。</p><h2>依据与条款链接</h2>{legal.map(([t,d,u])=><section key={u}><h3>{t}</h3><p>{d} <a className="button secondary" href={u} target="_blank" rel="noreferrer">查看原始条款</a></p></section>)}<div className="notice">最后核对：2026-08-04。许可与法律可能更新；发生冲突时，以原作品页面、许可全文和适用法律为准。</div></article></>}
