"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {usePathname} from "next/navigation";import type {LucideIcon} from "lucide-react";import {Archive,BookOpen,Camera,ChevronRight,ClipboardCheck,ClipboardList,FileText,Globe2,Home,Info,Languages,Map,Menu,Microscope,Moon,Mountain,PanelTop,Scale,Search,ShieldAlert,Sun,TestTubes,Waves,Wrench,X} from "lucide-react";
type NavItem=[string,string,LucideIcon];
const zh:NavItem[]=[["/","首页",Home],["/search","全站搜索",Search],["/project","项目控制台",PanelTop],["/atlas","真实图鉴",Camera],["/knowledge","知识库",BookOpen],["/geology","地质判断",Mountain],["/tools","工具与技术",Wrench],["/sampling","取样计算",TestTubes],["/qaqc","化验质控",ClipboardCheck],["/planner","取样规划",Microscope],["/field","样品记录",ClipboardList],["/map","样点地图",Map],["/reports","现场报告",FileText],["/backup","数据备份",Archive],["/sources","资料来源",Globe2],["/copyright","版权与免责声明",Scale],["/about","安全说明",ShieldAlert]];
const en:NavItem[]=[["/en","Home",Home],["/en/search","Search",Search],["/en/project","Project",PanelTop],["/en/atlas","Photo Atlas",Camera],["/en/knowledge","Knowledge Base",BookOpen],["/en/geology","Geology Interpretation",Mountain],["/en/tools","Tools & Techniques",Wrench],["/en/sampling","Sampling Tools",TestTubes],["/en/qaqc","Assay QA/QC",ClipboardCheck],["/en/planner","Sampling Design",Microscope],["/en/field","Sample Register",ClipboardList],["/en/map","Sample Mapping",Map],["/en/reports","Field Reports",FileText],["/en/backup","Data Backup",Archive],["/en/sources","References",Globe2],["/en/copyright","Copyright & Disclaimer",Scale],["/en/about","Safety",ShieldAlert]];
const my:NavItem[]=[["/my","ပင်မစာမျက်နှာ",Home],["/my#placer","ရွှေကျင်သိုက်",Waves],["/my#lode","မူလရွှေသိုက်",Mountain],["/my#minerals","သတ္တုခွဲခြားခြင်း",Camera],["/my#sampling","နမူနာနှင့် QA/QC",ClipboardCheck],["/my#safety","လုံခြုံရေးနှင့် ဥပဒေ",ShieldAlert],["/my#glossary","ဘူမိဗေဒဝေါဟာရ",BookOpen]];
const pairs:Record<string,string>={"/":"/en","/search":"/en/search","/project":"/en/project","/atlas":"/en/atlas","/knowledge":"/en/knowledge","/geology":"/en/geology","/tools":"/en/tools","/sampling":"/en/sampling","/qaqc":"/en/qaqc","/planner":"/en/planner","/field":"/en/field","/map":"/en/map","/reports":"/en/reports","/backup":"/en/backup","/sources":"/en/sources","/copyright":"/en/copyright","/about":"/en/about"};
export default function SiteNav(){
 const path=usePathname(),isEn=path.startsWith("/en"),isMy=path.startsWith("/my"),[open,setOpen]=useState(false),[theme,setTheme]=useState<"dark"|"light">("dark"),links=isMy?my:isEn?en:zh;
 useEffect(()=>{const saved=localStorage.getItem("goldfinder-theme"),next=saved==="light"||(!saved&&matchMedia("(prefers-color-scheme: light)").matches)?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next},[]);
 useEffect(()=>{document.documentElement.lang=isMy?"my":isEn?"en":"zh-CN"},[isMy,isEn]);
 useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);
 function toggle(){const next=theme==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem("goldfinder-theme",next)}
 const home=isMy?"/my":isEn?"/en":"/";const languageHref=isMy?"/":isEn?"/my":pairs[path]||"/en";const languageLabel=isMy?"中文":isEn?"မြန်မာ":"EN";const languageCode=isMy?"zh-CN":isEn?"my":"en";
 const openLabel=isMy?"လမ်းညွှန်ဖွင့်ရန်":isEn?"Open navigation":"打开导航",closeLabel=isMy?"လမ်းညွှန်ပိတ်ရန်":isEn?"Close navigation":"关闭导航";
 return <><header className="site-header"><Link className="brand" href={home} onClick={()=>setOpen(false)}><TestTubes size={21}/><span>{isMy?"ရွှေရှာဖွေ":isEn?"GOLDFINDER":"探金"}</span><small>GOLDFINDER</small></Link><div className="header-actions"><button className="icon-button" onClick={toggle} aria-label={theme==="dark"?(isEn?"Use light theme":"切换浅色模式"):(isEn?"Use dark theme":"切换深色模式")}>{theme==="dark"?<Sun size={18}/>:<Moon size={18}/>}</button><Link className="language-switch" href={languageHref} hrefLang={languageCode}><Languages size={16}/><span>{languageLabel}</span></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="site-menu" aria-label={open?closeLabel:openLabel}>{open?<X size={18}/>:<Menu size={18}/>}<span>{open?(isMy?"ပိတ်":isEn?"CLOSE":"关闭"):(isMy?"မီနူး":isEn?"MENU":"菜单")}</span></button></div></header><div id="site-menu" className={`nav-overlay ${open?"is-open":""}`} aria-hidden={!open}><div className="nav-inner"><p className="eyebrow">EXPLORE GOLDFINDER</p><nav>{links.map(([href,label,Icon])=><Link href={href} key={href} onClick={()=>setOpen(false)}><Icon size={19}/><b>{label}</b><ChevronRight size={17}/></Link>)}</nav><div className="nav-note"><Info size={20}/><strong>{isMy?"မြေပြင်ဆုံးဖြတ်ချက်အခြေခံ":isEn?"Field interpretation principle":"现场判断原则"}</strong><p>{isMy?"ကြည့်ရှုချက်သည် အပြီးသတ်အဖြေမဟုတ်ပါ။ ဓာတ်ပုံတစ်ပုံသည် သတ္တုအတည်ပြုချက်မဟုတ်ပါ။ ကိုယ်စားပြုနမူနာ၊ သင့်လျော်သော စမ်းသပ်မှုနှင့် ပြန်လည်စစ်ဆေးမှု လိုအပ်သည်။":isEn?"Observation is not a conclusion, and a photograph is not an identification. Verify every anomaly through representative sampling, fit-for-purpose analysis, and review.":"观察不是结论，图片不是鉴定。所有异常必须经过代表性取样、适用检测与复核。"}</p></div></div></div></>}
